spring:
  datasource:
    url: jdbc:mysql://localhost:3306/unide_db?serverTimezone=Asia/Seoul
    username: ${UNIDE_DB_USERNAME}
    password: ${UNIDE_DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  mail:
    host: smtp.zoho.com
    port: 587
    username: ${ZOHO_MAIL_USERNAME}
    password: ${ZOHO_MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          from: ${ZOHO_MAIL_USERNAME}

  jwt:
    secret-key: ${JWT_SECRET_KEY}
    access-token-expiration-ms: 3600000
    refresh-token-expiration-ms: 604800000

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            scope:
              - profile
              - email
              
          github:
            client-id: ${GITHUB_CLIENT_ID}
            client-secret: ${GITHUB_CLIENT_SECRET}
            scope:
              - user:email
              - read:user

file:
  upload-dir: ./uploads/portfolios

openai:
  api-key: ${OPENAI_API_KEY}
  model: gpt-4o-mini
  api-url: https://api.openai.com/v1/chat/completions

servlet:
  multipart:
    max-file-size: 100MB
    max-request-size: 500MB

app:
  base-url: http://localhost:8080
  upload:
    avatar-dir: uploads/avatars
    testcase-dir: uploads/testcases
    portfolio-dir: uploads/portfolios


